name: helloworld-evesa
version: git
summary: helloworld
description: >
  print helloWorld

grade : devel
confinement: devmode

base: core 18

parts:
  offlineimap:
    plugin: python
    python-version: python3
    source: .
    source-type: git
    

apps:
  helloworld-evesa:
    command: bin/helloworld