name: helloworld-evesa
version: git
summary: helloworld-evesa
description: >
  print helloWorld

confinement: devmode

parts:
  offlineimap:
    plugin: python
    python-version: python3
    source: https://github.com/tanguylp/helloWorld.git

apps:
  offlineimap:
    command: bin/helloworld-evesa